# Generated by Django 2.1rc1 on 2018-09-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=80)),
                ('whatsapp_number', models.CharField(max_length=13)),
                ('is_attending', models.BooleanField(choices=[(True, 'Will Attend'), (False, 'Will Not Attend')], default=None)),
                ('plus_one', models.BooleanField(choices=[(True, 'Yes!'), (False, 'No.')], default=None)),
                ('additional_names', models.CharField(blank=True, max_length=1000)),
                ('comments', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
