# Generated by Django 2.1rc1 on 2018-09-08 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='whatsapp_phone_number',
            field=models.CharField(default='0', help_text='Format: 85291790376', max_length=30, validators=[django.core.validators.RegexValidator(message='Format: AreaCode+Number - 6592962824.', regex='^\\d{9,15}$')]),
        ),
    ]
