# Generated by Django 2.1rc1 on 2018-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
