# Generated by Django 2.1rc1 on 2018-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='plus_one',
            field=models.BooleanField(choices=[(True, 'Yes.'), (False, 'No.')], default=None),
        ),
    ]
