# Generated by Django 2.1rc1 on 2018-09-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='last_name',
        ),
    ]
