# Generated by Django 2.1rc1 on 2018-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20180923_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='comments',
            field=models.CharField(max_length=1000),
        ),
    ]
