# Generated by Django 2.1rc1 on 2018-09-23 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_auto_20180923_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='whatsapp_phone_number',
            field=models.CharField(help_text='Format: 85291790376', max_length=30, validators=[django.core.validators.RegexValidator(message='Format: AreaCode+Number - 6592962824.', regex='^\\d{9,15}$')]),
        ),
    ]
