# Generated by Django 2.1rc1 on 2018-09-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_auto_20180923_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(choices=[(True, 'Will Attend'), (False, 'Will Not Attend')], default=None),
        ),
    ]
