# Generated by Django 2.1rc1 on 2018-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_auto_20180923_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
